### ISSUE TITLE
js error 

### ISSUE THREAD

**Issue by pressurejets** [dreimer1986/lovelace-animated-background#7]
Uncaught error from Edge 120.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'shadowRoot') /hacsfiles/lovelace-media-art-background/media-art-background.js:81:60
Uncaught error from Edge 120.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'shadowRoot') /hacsfiles/lovelace-media-art-background/media-art-background.js:81:147

**Comment by dreimer1986** [comment]
Uuuh, what is this? I only have a animated-background.js. I see these errors even though I don't use this addon anymore at all from time to time btw.

Otherwise I recommend to check my other solution as this one is just a hackfix to get this old addin work in newer HA versions with some unfixable nitpicks. As these were too much for my design choice to handle I stopped maintaining this addon.

https://github.com/dreimer1986/yourname_card_mod/blob/master/README-script.md New way made by me.
